// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZyojFbtz7d-QdfTcYEJZwuOPrY2Akd0g',
    appId: '1:942521666785:web:66645eede650e25e373ba0',
    messagingSenderId: '942521666785',
    projectId: 'bf-obc-flutter',
    authDomain: 'bf-obc-flutter.firebaseapp.com',
    storageBucket: 'bf-obc-flutter.firebasestorage.app',
    measurementId: 'G-2KK4SM09JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiLOkyU5ENKbuWSV1G-HZgL5bTM9Fha4w',
    appId: '1:942521666785:android:9f2fae267d2b2fe9373ba0',
    messagingSenderId: '942521666785',
    projectId: 'bf-obc-flutter',
    storageBucket: 'bf-obc-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9VOwBxCVZYS2QCWiQcgWCU4UQq_ZwOVQ',
    appId: '1:942521666785:ios:a79c5c0669c8dbc6373ba0',
    messagingSenderId: '942521666785',
    projectId: 'bf-obc-flutter',
    storageBucket: 'bf-obc-flutter.firebasestorage.app',
    iosBundleId: 'com.example.brokerFlutterPp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9VOwBxCVZYS2QCWiQcgWCU4UQq_ZwOVQ',
    appId: '1:942521666785:ios:a79c5c0669c8dbc6373ba0',
    messagingSenderId: '942521666785',
    projectId: 'bf-obc-flutter',
    storageBucket: 'bf-obc-flutter.firebasestorage.app',
    iosBundleId: 'com.example.brokerFlutterPp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZyojFbtz7d-QdfTcYEJZwuOPrY2Akd0g',
    appId: '1:942521666785:web:eef756611e9c75ae373ba0',
    messagingSenderId: '942521666785',
    projectId: 'bf-obc-flutter',
    authDomain: 'bf-obc-flutter.firebaseapp.com',
    storageBucket: 'bf-obc-flutter.firebasestorage.app',
    measurementId: 'G-CGHXDHTZHX',
  );
}
