// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxmgWeGJIkknyK09OCodKEkp_w4tw_-eU',
    appId: '1:155217089865:web:b95e1616d6047587507698',
    messagingSenderId: '155217089865',
    projectId: 'obcflutter',
    authDomain: 'obcflutter.firebaseapp.com',
    databaseURL: 'https://obcflutter-default-rtdb.firebaseio.com',
    storageBucket: 'obcflutter.appspot.com',
    measurementId: 'G-F2L431PMS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJhcirGyQXqELNC5s1fcKcS9a5nVBK5EE',
    appId: '1:155217089865:android:d678dbd733983609507698',
    messagingSenderId: '155217089865',
    projectId: 'obcflutter',
    databaseURL: 'https://obcflutter-default-rtdb.firebaseio.com',
    storageBucket: 'obcflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUuc73L-SjzqsbeZ-oOhy0vDMi7xHqkXU',
    appId: '1:155217089865:ios:b808f353d98e260c507698',
    messagingSenderId: '155217089865',
    projectId: 'obcflutter',
    databaseURL: 'https://obcflutter-default-rtdb.firebaseio.com',
    storageBucket: 'obcflutter.appspot.com',
    iosBundleId: 'com.example.brokerFlutterPp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUuc73L-SjzqsbeZ-oOhy0vDMi7xHqkXU',
    appId: '1:155217089865:ios:b808f353d98e260c507698',
    messagingSenderId: '155217089865',
    projectId: 'obcflutter',
    databaseURL: 'https://obcflutter-default-rtdb.firebaseio.com',
    storageBucket: 'obcflutter.appspot.com',
    iosBundleId: 'com.example.brokerFlutterPp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxmgWeGJIkknyK09OCodKEkp_w4tw_-eU',
    appId: '1:155217089865:web:d6b65141911bff2a507698',
    messagingSenderId: '155217089865',
    projectId: 'obcflutter',
    authDomain: 'obcflutter.firebaseapp.com',
    databaseURL: 'https://obcflutter-default-rtdb.firebaseio.com',
    storageBucket: 'obcflutter.appspot.com',
    measurementId: 'G-2YN7B192RB',
  );
}
